name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Node.js 버전 (필요에 따라 수정)

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: CI=false npm run build  # 빌드 명령 (예: React, Next.js)

    - name: Decode SSH key
      run: echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa

    - name: Set SSH key permissions
      run: chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        scp -i ~/.ssh/id_rsa -r ./build/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.TARGET_DIR }}
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        sudo systemctl restart my-app  # 필요하면 애플리케이션 재시작
        EOF
