name: Deploy to EC2

on:
  push:
    branches: [main]  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      # GitHub Repository에서 Checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # SSH 비공개 키 설정
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 배포 스크립트를 실행
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@deepdivers.store << 'EOF'
            cd /home/front/team-project-front
            git pull origin main
            npm install
          EOF
